language: ruby
rvm:
- 2.0.0
- 2.1.0
deploy:
  provider: heroku
  api_key:
    secure: alxddvlSdf/O5BYEXfCHIXETgnFLxTUckgJJBC8mypoDU/+ATQfBNsUIL8LmjdV9uHp6SpT9LH2oyGyWgd888aM71HDKlUwmfolZnPtIwQC8pf77bTZpYshApzpIOoJQvu1keSwEHrI+BQoYQ2XJL7wFNXD7E711qju6EbTUhcs=
  run: 
    - "rake db:schema:load"
    - "rake db:migrate RAILS_ENV=staging"
    - "rake db:seed"
  app: ontapstaging
  on:
    branch: staging
    rvm: 2.0.0
  buildpack: https://github.com/Orasi/heroku-buildpack-ruby.git
